name: "Manage Pull Requests"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:

  manage_pull_requests:
    name: Manage pull requests
    uses: arghpy/shared-workflows/.github/workflows/lint.yaml@manage_prs_workflow
    secrets: inherit
    with:
      runner: ${{ vars.RUNNER }}
